### ISSUE TITLE
new terms for pathogen sampling sites

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [AgriculturalSemantics/agro#31]
We have a number of terms it seems AGRO is the best home for?!  For a number of entries that have basic definitions I marked myself as source, but I don't need to be mentioned unless you need that.	

parent: ENVO_0010003	agricultural environmental material
term: **crop**		
definition: A crop is any cultivated plant, fungus, or alga that is harvested for food, clothing, livestock, fodder, biofuel, medicine, or other uses.
source: https://en.wikipedia.org/wiki/Crop

parent: ENVO_0010003	agricultural environmental material
term: **forage**	
definition: The vegetation of tended pasture, consists mainly of grasses, with an interspersion of legumes and other forbs (non-grass herbaceous plants)
source: https://en.wikipedia.org/wiki/Pasture

parent: ENVO_00000077	agricultural feature
term: **pasture**
definition: Pasture is land used for grazing.
source: https://en.wikipedia.org/wiki/Pasture

parent: ENVO_00000077	agricultural feature
term: **feed storage**
definition: Feed storage is any physical space or structure used to store agricultural animal feed	
source: (Damion Dooley)

parent: ENVO_00000077	agricultural feature
term: **manure storage**
definition: Manure storage is any physical space or structure used to store manure
source: (Damion Dooley)

parent: ENVO_00003031	animal manure
term: **bovine dairy liquid manure**
definition: bovine (dairy liquid) manure is manure collected directly or indirectly from dairy cattle, as from flushing of manure from concrete feed lanes, free stalls, and milking facilities
source: http://manuremanagement.ucdavis.edu/files/134369.pdf

parent: ENVO_00003031	animal manure
term: **poultry manure**
definition: Poultry manure is manure originating from poultry
source: (Damion Dooley)

parent: ENVO_00003031	animal manure
term: **heat treated animal manure**
definition: Heat treated animal manure is animal manure subject to heat treatment for solidification or sterilization purposes.
source: (Damion Dooley)

parent: ENVO_00003031	animal manure
term: **composted animal manure**
definition: Composted animal manure is animal manure subjected to a composting process.
source: (Damion Dooley)

parent: ENVO_00003031	animal manure
term: **animal manure product**
definition: An animal manure product is heat treated animal manure processed into a product for commercial or consumer use.	
source: (Damion Dooley)

**Comment by Public-Health-Bioinformatics** [comment]
Ah, @marieALaporte  I forgot "crop" has already been defined in AgrO as you mention in Envo #460. You can scratch that one.
But what about the animal feed items - 
    
    fish meal: http://purl.obolibrary.org/obo/AGRO_00000083
    blood meal: http://purl.obolibrary.org/obo/AGRO_00000086

Should these be moved over to FoodOn?  Any other animal food categories like that too?

**Comment by pbuttigieg** [comment]
Compelled to be brief right now, but let's recall that we need a very
careful and principled approach to the ENVO-FOODON-AGRO balance. We arrived
at a general policy some time back, IIRC...

**Comment by Public-Health-Bioinformatics** [comment]
Ok, could the AgrO mission statement be restated again here, esp. in relation to ENVO?  I just have from ENVO #460 that "I'm placing all animal-related terms in ENVO to prevent mission creep for AgrO", and that FoodOn should take food related terms for both humans and animals.

**Comment by pbuttigieg** [comment]
@cmungall @marieALaporte please chime in if this is off:

From the README.Md AGRO concerns itself with the domain of "agronomic practices, agronomic techniques, and agronomic variables". For development convenience and due to pressing deployment schedules, AGRO also has classes for the equipment used in the techniques and practices, which may be moved at a later stage.

The practices and techniques will be under some  `planned process` and `agronomic variables` will be partly represented using qualities (e.g. "temperature of soil").  Most of the latter are of general interest and are ENVO classes. @marieALaporte is working to extend ENVO's patterns to produce these terms quickly https://github.com/EnvironmentOntology/envo/issues/492 . However, some of these qualities are so closely tied to the content of AGRO (i.e. they are defined by an AGRO-specific understanding of a technique), that they live therein (e.g. #14 #15). 

A lot of the material entities relevant to AGRO are also of general interest outside agronomy (e.g. `manure`, `vehicles`, etc) and thus should either be minted in or eventually moved to ENVO (unless a more specific domain ontology emerges, like a manure or vehicle ontology) and be imported to AGRO. This is both a domain issue and also practical one as we can axiomatise more in ENVO for the moment. If there are derived terms that are strongly flavoured by AGRO semantics (e.g. are the output of a process that is the realisation of an AGRO technique), those can certainly live in AGRO itself. 

This somewhat modifies the position in https://github.com/EnvironmentOntology/envo/issues/460 , in that classes like...

>```
>subclass of http://purl.obolibrary.org/obo/ENVO_00000042 #    agricultural - drainage canal
>subclass of http://purl.obolibrary.org/obo/ENVO_00000140 #    agricultural - drainage ditch
># http://purl.obolibrary.org/obo/ # edit    agricultural - storage - feed
># http://purl.obolibrary.org/obo/ # edit    agricultural - storage - manure
>```

...would be better hosted in ENVO as we can weave them in with our building and topology semantics; however, classes like...
```
# http://purl.obolibrary.org/obo/ #    agricultural - crop
```
...should go in AGRO as it's clearly contained in the agronomy domain and AGRO would likely have a technique/process like crop cultivation for axiomatisation. ENVO would then import it if needed.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I'm fine with closing the above item and moving most of the defn. requests over to ENVO.
